services:
  postgres:
    container_name: pr-svc_postgres
    image: postgres:18.0
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 3
    hostname: pr-svc_postgres
    networks:
      - pr-svc_network
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  pr-svc_network:
    driver: bridge

volumes:
  postgres-data: