name: pr service golint check

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Run Golint
    runs-on: ubuntu-latest
    container: 
      image: golang:1.24.10-alpine
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install golint
      run: |
        go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.6.2

    - name: Run golint
      run: |
        golangci-lint -set_exit_status ./...